import requests

def main() -> None:
    response = requests.get("https://fantasy.trashtalk.co/?tpl=historique",
                            headers={"Cookie": "euconsent-v2=CQdCiAAQdCiAABcAKEFRCLFoAP_gAEPgAAqIJNNB_G_dSSFj8TJ3YftkeYxH5dAj7sQxBgaJgyQFyBLEoJwXgmAAIAjKAKAKGBIAskBAIQBlCAjABUAAAIABISCMIECQAQAAJqBEAEMRAmJICBBJGQAgGAAQglgEAhQAgQsEyFooQNxAAIAABQAAAAAhAJCBAAAIBDggQBAQAAAAAggAEABAAAAAAAAEAlAIAAAIAAEEmgATDQqIICwIAAgEDCCBAAoIggAoEAQAAJAwQAAJAgCUAYACDABAAAFAAAEAAAAQQAAAAAAgAQgACAAAEAAEAgEAAAAAAAAABAgAAAAgRAAAAAEAIAQAAAAAAADAAgAQIQAAAgAICgAAAAQAgAAAAAAAEBAAAAAAAAQAAAAAAAAAQAAAAAAAAAAAAAAAAAECAAAAAAAA.IJNNB_G_dSSFn8TJ3YftkeYxX5dAj7sQxBgaJgyQFyBLEoJwXkmACIAjKAKAKGBIAskBAIQBlCAjABUAAAIABITCMIECQAQAAJqBEAEMRAmJICBBJGQAgGAAQglgGAhQAgQsEyFooQNxAAIAgBQAAAAAhAJCBAAAIBDggQBAQAAAAAggAEABAAAAAAAAEAlAIEAAIAAE.0HQ_bwQ.4U6gDgBZASWBEkEUoKDAUIgp1AFQAwABAACoAMgA0ACEAE0AKAApgBWAFkALgA3gByAIEAQgBPACjAFMAVABUABAAQAD6AAAAAAA; TTFLmail=guillaume.delbarre.gde%40gmail.com; TTFLhash=2dcbc52afc01e0e2440c69553716f2166a74ce5cd37c142f43d0554fc10fd2e9; PHPSESSID=64knb85l82dop9qls7u8ekk5k4"})
    
    print(response.status_code)
    print(response.text)

if __name__ == "__main__":
    main()